### ISSUE TITLE
-v flag changes IDAT calculations

### ISSUE THREAD

**Issue by turnipsoup** [sherlly/PCRT#5]
Hello!

When using this program to examine a PNG file I have noticed it will give a different pass/fail answer depending on if the verbose flag is used. Please see offset: 0x1208D for the example below.

```
PhillipJFryIV dl/PCRT ‹master*› » python PCRT.py  -i ../work/third_flag.png

	 ____   ____ ____ _____
	|  _ \ / ___|  _ \_   _|
	| |_) | |   | |_) || |
	|  __/| |___|  _ < | |
	|_|    \____|_| \_\|_|

	PNG Check & Repair Tool

Project address: https://github.com/sherlly/PCRT
Author: sherlly
Version: 1.1

[Finished] Correct PNG header
[Finished] Correct IHDR CRC (offset: 0x1D): 352CF570
[Finished] IHDR chunk check complete (offset: 0x8)
[Finished] Correct IDAT chunk data length (offset: 0x21 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x2029): 881A7BE3
[Finished] Correct IDAT chunk data length (offset: 0x202D length: 2000)
[Finished] Correct IDAT CRC (offset: 0x4035): 2824D3AD
[Finished] Correct IDAT chunk data length (offset: 0x4039 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x6041): 4D15FD74
[Finished] Correct IDAT chunk data length (offset: 0x6045 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x804D): 5B1C8ADA
[Finished] Correct IDAT chunk data length (offset: 0x8051 length: 2000)
[Finished] Correct IDAT CRC (offset: 0xA059): DC9DDA2D
[Finished] Correct IDAT chunk data length (offset: 0xA05D length: 2000)
[Finished] Correct IDAT CRC (offset: 0xC065): BBDF9BD6
[Finished] Correct IDAT chunk data length (offset: 0xC069 length: 2000)
[Finished] Correct IDAT CRC (offset: 0xE071): 35CC1FE8
[Finished] Correct IDAT chunk data length (offset: 0xE075 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x1007D): A4C00BAB
[Finished] Correct IDAT chunk data length (offset: 0x10081 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x12089): 8F95B8C7
[Detected] Error IDAT chunk data length! (offset: 0x1208D)
chunk length:2B5
actual length:2C1
[Notice] Try fixing it? (y or n) [default:y] ^[[A^[[A^CTraceback (most recent call last):
  File "PCRT.py", line 780, in <module>
    my_png.CheckPNG()
  File "PCRT.py", line 429, in CheckPNG
    res,idat=self.CheckIDAT(data)
  File "PCRT.py", line 600, in CheckIDAT
    choice=raw_input(msg)
KeyboardInterrupt
PhillipJFryIV dl/PCRT ‹master*› » python PCRT.py -v -i ../work/third_flag.png                                                                1 ↵

	 ____   ____ ____ _____
	|  _ \ / ___|  _ \_   _|
	| |_) | |   | |_) || |
	|  __/| |___|  _ < | |
	|_|    \____|_| \_\|_|

	PNG Check & Repair Tool

Project address: https://github.com/sherlly/PCRT
Author: sherlly
Version: 1.1

[Finished] Correct PNG header
[Finished] Correct IHDR CRC (offset: 0x1D): 352CF570
[Finished] IHDR chunk check complete (offset: 0x8)
[Finished] Correct IDAT chunk data length (offset: 0x21 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x2029): 881A7BE3
[Finished] Correct IDAT chunk data length (offset: 0x202D length: 2000)
[Finished] Correct IDAT CRC (offset: 0x4035): 2824D3AD
[Finished] Correct IDAT chunk data length (offset: 0x4039 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x6041): 4D15FD74
[Finished] Correct IDAT chunk data length (offset: 0x6045 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x804D): 5B1C8ADA
[Finished] Correct IDAT chunk data length (offset: 0x8051 length: 2000)
[Finished] Correct IDAT CRC (offset: 0xA059): DC9DDA2D
[Finished] Correct IDAT chunk data length (offset: 0xA05D length: 2000)
[Finished] Correct IDAT CRC (offset: 0xC065): BBDF9BD6
[Finished] Correct IDAT chunk data length (offset: 0xC069 length: 2000)
[Finished] Correct IDAT CRC (offset: 0xE071): 35CC1FE8
[Finished] Correct IDAT chunk data length (offset: 0xE075 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x1007D): A4C00BAB
[Finished] Correct IDAT chunk data length (offset: 0x10081 length: 2000)
[Finished] Correct IDAT CRC (offset: 0x12089): 8F95B8C7
[Finished] Correct IDAT chunk data length (offset: 0x1208D length: 2B5)
[Finished] Correct IDAT CRC (offset: 0x1234A): 929B5826
[Finished] IDAT chunk check complete (offset: 0x21)
[Finished] Correct IEND chunk
[Finished] IEND chunk check complete
[Finished] PNG check complete
[Notice] Show the repaired image? (y or n) [default:n] n
```

**Comment by burpy** [comment]
I have the same issue. It shows two errors without verbose and only one error with verbose:

```
user@server:/PCRT# python PCRT.py -i /path/to/image.png

	 ____   ____ ____ _____ 
	|  _ \ / ___|  _ \_   _|
	| |_) | |   | |_) || |  
	|  __/| |___|  _ < | |  
	|_|    \____|_| \_\|_|  

	PNG Check & Repair Tool 

Project address: https://github.com/sherlly/PCRT
Author: sherlly
Version: 1.1
	
[Finished] Correct PNG header
[Finished] Correct IHDR CRC (offset: 0x1D): DEAD50AB
[Finished] IHDR chunk check complete (offset: 0x8)
[Finished] Correct IDAT chunk data length (offset: 0xCAC length: 287)
[Finished] Correct IDAT CRC (offset: 0xF3B): C6851473
[Detected] Error IDAT chunk data length! (offset: 0xF3F)
chunk length:25
actual length:B9
[Notice] Try fixing it? (y or n) [default:y] y
[Warning] Only fix because of DOS->Unix conversion
[Failed] Fixing failed, auto discard this operation...
[Detected] Error IDAT chunk data length! (offset: 0x1004)
chunk length:25
actual length:AD
[Notice] Try fixing it? (y or n) [default:y] y
[Warning] Only fix because of DOS->Unix conversion
[Failed] Fixing failed, auto discard this operation...
[Finished] IDAT chunk check complete (offset: 0xCAC)
[Finished] Correct IEND chunk
[Finished] IEND chunk check complete
[Finished] PNG check complete
[Notice] Show the repaired image? (y or n) [default:n] n
```

and with -v

```
user@server:/PCRT# python PCRT.py -v -i /path/to/image.png

	 ____   ____ ____ _____ 
	|  _ \ / ___|  _ \_   _|
	| |_) | |   | |_) || |  
	|  __/| |___|  _ < | |  
	|_|    \____|_| \_\|_|  

	PNG Check & Repair Tool 

Project address: https://github.com/sherlly/PCRT
Author: sherlly
Version: 1.1
	
[Finished] Correct PNG header
[Finished] Correct IHDR CRC (offset: 0x1D): DEAD50AB
[Finished] IHDR chunk check complete (offset: 0x8)
[Detected] Error IDAT chunk data length! (offset: 0xCAC)
chunk length:287
actual length:340
[Notice] Try fixing it? (y or n) [default:y] y
[Warning] Only fix because of DOS->Unix conversion
[Failed] Fixing failed, auto discard this operation...
[Finished] IDAT chunk check complete (offset: 0xCAC)
[Finished] Correct IEND chunk
[Finished] IEND chunk check complete
[Finished] PNG check complete
[Notice] Show the repaired image? (y or n) [default:n] n
```

**Comment by sherlly** [comment]
Thanks for all of your comments, actually it is not an issue. The verbose(-v) flag is used as a safe way to recover the image, while without it means that the tool assume all IDAT chunk length are correct. That's why the different result you got when using the tool.
